"""adding other column

Revision ID: 4433b05b30be
Revises: 768a37106c46
Create Date: 2019-09-21 16:05:24.627861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4433b05b30be'
down_revision = '768a37106c46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category', sa.String(length=255), nullable=True))
    op.add_column('pitches', sa.Column('pitch', sa.String(length=255), nullable=True))
    op.drop_column('pitches', 'post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('post', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'pitch')
    op.drop_column('pitches', 'category')
    # ### end Alembic commands ###
