"""adding other tables

Revision ID: 768a37106c46
Revises: a65e3fd5df5d
Create Date: 2019-09-21 14:25:01.853817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768a37106c46'
down_revision = 'a65e3fd5df5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pitches', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('title', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'pitches', 'category', ['category_id'], ['id'])
    op.drop_column('pitches', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'title')
    op.drop_column('pitches', 'category_id')
    op.drop_table('category')
    # ### end Alembic commands ###
